"""baseline_full_schema

Revision ID: 47beea1df0c1
Revises: 
Create Date: 2026-05-31 16:53:23.781688
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47beea1df0c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=True),
    sa.Column('preset', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('creative_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('predicted_ctr', sa.Float(), nullable=True),
    sa.Column('chosen', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_variants_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_variants_user_id'), ['user_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contract_text', sa.Text(), nullable=True),
    sa.Column('signed_by_seller', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index('ix_deals_seller', ['seller_id'], unique=False)
        batch_op.create_index('ix_deals_status', ['status'], unique=False)
        batch_op.create_index('ix_deals_supplier', ['supplier_id'], unique=False)

    op.create_table('ideas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('import_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temp_path', sa.String(length=500), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_records_user_id'), ['user_id'], unique=False)

    op.create_table('imported_finance_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('logistics', sa.Float(), nullable=False),
    sa.Column('ad_spend', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_finance_rows', schema=None) as batch_op:
        batch_op.create_index('ix_imp_finance_user_mp', ['user_id', 'marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_finance_rows_import_id'), ['import_id'], unique=False)

    op.create_table('imported_product_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_product_rows', schema=None) as batch_op:
        batch_op.create_index('ix_imp_product_user_mp', ['user_id', 'marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_product_rows_import_id'), ['import_id'], unique=False)

    op.create_table('insight_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('insight_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight_records', schema=None) as batch_op:
        batch_op.create_index('ix_insight_user_key', ['user_id', 'insight_key'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)

    op.create_table('monitor_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('affected_module', sa.String(length=50), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name='uq_monitor_event_title')
    )
    op.create_table('operator_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('action_taken', sa.String(length=30), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('resolved_after_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('effect_observed', sa.String(length=30), nullable=True),
    sa.Column('effect_duration_days', sa.Integer(), nullable=True),
    sa.Column('recurrence_after_days', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_op_decision_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_op_decision_user_type', ['user_id', 'insight_type'], unique=False)

    op.create_table('promo_code_activations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('promo_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_id', 'user_id', name='uq_promo_user')
    )
    with op.batch_alter_table('promo_code_activations', schema=None) as batch_op:
        batch_op.create_index('ix_promo_act_promo', ['promo_id'], unique=False)
        batch_op.create_index('ix_promo_act_user', ['user_id'], unique=False)

    op.create_table('promo_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_plans', sa.String(length=100), nullable=False),
    sa.Column('max_activations', sa.Integer(), nullable=True),
    sa.Column('current_activations', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blogger_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index('ix_promo_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)

    op.create_table('referral_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_referral_invitee')
    )
    with op.batch_alter_table('referral_records', schema=None) as batch_op:
        batch_op.create_index('ix_referral_referrer', ['referrer_id'], unique=False)

    op.create_table('seo_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('preset', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('typography_preset', sa.String(length=50), nullable=True),
    sa.Column('current_price', sa.String(length=50), nullable=True),
    sa.Column('old_price', sa.String(length=50), nullable=True),
    sa.Column('advantages_json', sa.Text(), nullable=True),
    sa.Column('template_set', sa.String(length=50), nullable=True),
    sa.Column('image_urls_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seo_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_projects_user_id'), ['user_id'], unique=False)

    op.create_table('seo_rebuilds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('preset', sa.String(length=50), nullable=False),
    sa.Column('typography_preset', sa.String(length=50), nullable=True),
    sa.Column('bigger_product_mode', sa.Boolean(), nullable=True),
    sa.Column('minimal_text_mode', sa.Boolean(), nullable=True),
    sa.Column('warm_gradient_mode', sa.Boolean(), nullable=True),
    sa.Column('high_contrast_mode', sa.Boolean(), nullable=True),
    sa.Column('rebuild_reason', sa.String(length=60), nullable=False),
    sa.Column('rebuild_context_json', sa.Text(), nullable=True),
    sa.Column('ctr_before', sa.Float(), nullable=True),
    sa.Column('ctr_after', sa.Float(), nullable=True),
    sa.Column('delta_ctr_percent', sa.Float(), nullable=True),
    sa.Column('impressions_count', sa.Integer(), nullable=True),
    sa.Column('revenue_before', sa.Float(), nullable=True),
    sa.Column('revenue_after', sa.Float(), nullable=True),
    sa.Column('delta_revenue', sa.Float(), nullable=True),
    sa.Column('expected_gain_rub', sa.Float(), nullable=True),
    sa.Column('actual_gain_rub', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('confidence_level', sa.String(length=10), server_default='low', nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seo_rebuilds', schema=None) as batch_op:
        batch_op.create_index('ix_seo_rebuild_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_seo_rebuild_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_seo_rebuild_user_mp_cat', ['user_id', 'marketplace', 'category'], unique=False)
        batch_op.create_index('ix_seo_rebuild_user_product', ['user_id', 'product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_rebuilds_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_sr_reviewer', ['reviewer_id'], unique=False)
        batch_op.create_index('ix_sr_target', ['target_type', 'target_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_deals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_industry', ['industry'], unique=False)
        batch_op.create_index('ix_suppliers_region', ['region'], unique=False)
        batch_op.create_index('ix_suppliers_verified', ['is_verified'], unique=False)

    op.create_table('telegram_notification_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_key', sa.String(length=300), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_notification_log', schema=None) as batch_op:
        batch_op.create_index('ix_tnl_user_key', ['user_id', 'notification_key'], unique=False)
        batch_op.create_index('ix_tnl_user_sent', ['user_id', 'sent_at'], unique=False)

    op.create_table('transport_companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('delivery_types', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('price_per_m3', sa.Float(), nullable=True),
    sa.Column('min_transit_days', sa.Integer(), nullable=True),
    sa.Column('max_transit_days', sa.Integer(), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_companies', schema=None) as batch_op:
        batch_op.create_index('ix_tc_region', ['region'], unique=False)

    op.create_table('user_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_scope', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.create_index('ix_user_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_events_user_type', ['user_id', 'event_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(length=50), server_default='master', nullable=False),
    sa.Column('chat_violations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chat_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('was_referrer', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('was_referred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_restored', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('registered_ip', sa.String(length=45), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfa_secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_secrets_user_id'), ['user_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_uid')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_accounts_user_id', ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tariff', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_yookassa_payment_id'), ['yookassa_payment_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('auto_mode', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('uscc', sa.String(length=18), nullable=True),
    sa.Column('business_scope', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_source', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_verifications_status', ['status'], unique=False)
        batch_op.create_index('ix_supplier_verifications_user_id', ['user_id'], unique=False)

    op.create_table('telegram_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notify_bad_review', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_offer_change', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_price_drop', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_negative_review', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_trial_end', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_insights', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_seo_opportunity', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_sales_growth', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_retention', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('retention_inactive_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('notify_weekly_report', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_ab_results', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('daily_report', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('daily_report_time', sa.String(length=5), nullable=False),
    sa.Column('weekly_summary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('weekly_summary_day', sa.String(length=10), nullable=False),
    sa.Column('weekly_summary_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('telegram_settings', schema=None) as batch_op:
        batch_op.create_index('ix_telegram_settings_user_id', ['user_id'], unique=False)

    op.create_table('competitor_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('competitor_url', sa.String(length=512), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('sales_estimate', sa.Integer(), nullable=True),
    sa.Column('significance', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('marketplace_fee', sa.Float(), nullable=False),
    sa.Column('ad_spend', sa.Float(), nullable=False),
    sa.Column('cogs', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('margin_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_change_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('target_position', sa.String(length=50), nullable=False),
    sa.Column('target_percent', sa.Float(), nullable=False),
    sa.Column('reaction_threshold', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('auto_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('review_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_responses')
    op.drop_table('pricing_rules')
    op.drop_table('price_change_log')
    op.drop_table('legal_cases')
    op.drop_table('financial_snapshots')
    op.drop_table('competitor_analysis')
    with op.batch_alter_table('telegram_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_settings_user_id')

    op.drop_table('telegram_settings')
    with op.batch_alter_table('supplier_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_verifications_user_id')
        batch_op.drop_index('ix_supplier_verifications_status')

    op.drop_table('supplier_verifications')
    op.drop_table('success_stories')
    op.drop_table('products')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_yookassa_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    op.drop_table('payments')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_accounts_user_id')

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id')

    op.drop_table('notifications')
    with op.batch_alter_table('mfa_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_secrets_user_id'))

    op.drop_table('mfa_secrets')
    op.drop_table('chat_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_index('ix_user_events_user_type')
        batch_op.drop_index(batch_op.f('ix_user_events_user_id'))
        batch_op.drop_index('ix_user_events_user_created')

    op.drop_table('user_events')
    with op.batch_alter_table('transport_companies', schema=None) as batch_op:
        batch_op.drop_index('ix_tc_region')

    op.drop_table('transport_companies')
    with op.batch_alter_table('telegram_notification_log', schema=None) as batch_op:
        batch_op.drop_index('ix_tnl_user_sent')
        batch_op.drop_index('ix_tnl_user_key')

    op.drop_table('telegram_notification_log')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('ix_suppliers_verified')
        batch_op.drop_index('ix_suppliers_region')
        batch_op.drop_index('ix_suppliers_industry')

    op.drop_table('suppliers')
    with op.batch_alter_table('supplier_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_sr_target')
        batch_op.drop_index('ix_sr_reviewer')

    op.drop_table('supplier_reviews')
    with op.batch_alter_table('seo_rebuilds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_rebuilds_user_id'))
        batch_op.drop_index('ix_seo_rebuild_user_product')
        batch_op.drop_index('ix_seo_rebuild_user_mp_cat')
        batch_op.drop_index('ix_seo_rebuild_user_id')
        batch_op.drop_index('ix_seo_rebuild_user_created')

    op.drop_table('seo_rebuilds')
    with op.batch_alter_table('seo_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_projects_user_id'))

    op.drop_table('seo_projects')
    with op.batch_alter_table('referral_records', schema=None) as batch_op:
        batch_op.drop_index('ix_referral_referrer')

    op.drop_table('referral_records')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))
        batch_op.drop_index('ix_promo_active')

    op.drop_table('promo_codes')
    with op.batch_alter_table('promo_code_activations', schema=None) as batch_op:
        batch_op.drop_index('ix_promo_act_user')
        batch_op.drop_index('ix_promo_act_promo')

    op.drop_table('promo_code_activations')
    with op.batch_alter_table('operator_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_op_decision_user_type')
        batch_op.drop_index('ix_op_decision_user_created')

    op.drop_table('operator_decisions')
    op.drop_table('monitor_events')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('insight_records', schema=None) as batch_op:
        batch_op.drop_index('ix_insight_user_key')

    op.drop_table('insight_records')
    with op.batch_alter_table('imported_product_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_product_rows_import_id'))
        batch_op.drop_index('ix_imp_product_user_mp')

    op.drop_table('imported_product_rows')
    with op.batch_alter_table('imported_finance_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_finance_rows_import_id'))
        batch_op.drop_index('ix_imp_finance_user_mp')

    op.drop_table('imported_finance_rows')
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_records_user_id'))

    op.drop_table('import_records')
    op.drop_table('ideas')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index('ix_deals_supplier')
        batch_op.drop_index('ix_deals_status')
        batch_op.drop_index('ix_deals_seller')

    op.drop_table('deals')
    with op.batch_alter_table('creative_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_variants_user_id'))
        batch_op.drop_index(batch_op.f('ix_creative_variants_session_id'))

    op.drop_table('creative_variants')
    # ### end Alembic commands ###
